# Generated by Django 2.2.7 on 2019-11-17 18:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('character_class', models.CharField(choices=[('Warrior', 'Warrior'), ('Paladin', 'Paladin'), ('Shadow Knight', 'Shadow Knight'), ('Beastlord', 'Beastlord'), ('Berserker', 'Berserker'), ('Monk', 'Monk'), ('Ranger', 'Ranger'), ('Rogue', 'Rogue'), ('Magician', 'Magician'), ('Necromancer', 'Necromancer'), ('Wizard', 'Wizard'), ('Bard', 'Bard'), ('Enchanter', 'Enchanter'), ('Cleric', 'Cleric'), ('Druid', 'Druid'), ('Shaman', 'Shaman')], max_length=20)),
                ('status', models.CharField(choices=[('MN', 'Main'), ('ALT', 'Alt'), ('REC', 'Recruit'), ('INA', 'Inactive')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='RaidDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('attendance_value', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('filename', models.CharField(max_length=50)),
                ('award_type', models.CharField(choices=[('Time', 'Time'), ('Boss Kill', 'Boss Kill'), ('Other', 'Other')], max_length=2)),
                ('notes', models.TextField(blank=True, default='')),
                ('characters_present', models.ManyToManyField(related_name='raid_dumps', to='padkp_show.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('notes', models.TextField(blank=True, default='')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padkp_show.Character')),
            ],
        ),
        migrations.CreateModel(
            name='DkpSpecialAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('attendance_value', models.IntegerField()),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.utcnow)),
                ('notes', models.TextField(blank=True, default='')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padkp_show.Character')),
            ],
        ),
    ]
