# Generated by Django 2.2.6 on 2019-10-26 02:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('MN', 'Main'), ('ALT', 'Alt'), ('REC', 'Recruit'), ('INA', 'Inactive')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime(2019, 10, 26, 2, 3, 12, 628919))),
                ('notes', models.TextField(blank=True, default='')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padkp_show.Character')),
            ],
        ),
        migrations.CreateModel(
            name='DkpAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_type', models.CharField(choices=[('TA', 'Time'), ('BK', 'Boss Kill'), ('?', 'Other')], max_length=2)),
                ('value', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime(2019, 10, 26, 2, 3, 12, 628389))),
                ('notes', models.TextField(blank=True, default='')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padkp_show.Character')),
            ],
        ),
    ]
